name: lunofono_bundle
description: A library to manage content bundles for the Lunofono, the media
   player for kids.
version: 1.0.0
repository: https://github.com/lunofono/lunofono_bundle

# To be removed when it is published
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  test: ^1.15.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
